### ISSUE TITLE
Can't build for web in Windows

### ISSUE THREAD

**Issue by BctfN0HUK7Yg** [emilk/eframe_template#43] opened 2022-01-09 18:24 UTC
I use gitbash to build web. With version 0.15 everything works right. 
With 0.16  I have problems with JQ and WASM-OPT.
First one I found and download, second - I remove from script (-fast arg isn't enough).
Now I can build my app for web. But it didn't work

**Comment by emilk** [comment] 2022-01-09 21:35
I don't have a windows machine. Perhaps you can help fix it?

In any case, an issue with "didn't work" isn't actionable. You need to add details. I'm sure your shell didn't print `didn't work` and closed, or did it?

![little-britain-computer-says-no](https://user-images.githubusercontent.com/1148717/148701858-d6ffc061-fac8-4718-a808-6d29664ce8fd.gif)

**Comment by BctfN0HUK7Yg** [comment] 2022-01-10 08:33
Ok, sorry. I wrote that message from phone and haven't access to logs.
There is a console log from Chrome
![Безымянный](https://user-images.githubusercontent.com/24766907/148737180-ba617bd1-2a2e-4b49-a778-2dd7e7989595.png)

**Comment by emilk** [comment] 2022-01-10 21:35
Duplicate of https://github.com/emilk/egui/issues/1087

**Closed by emilk** 2022-01-10 21:35 UTC
